[project]
name = "FakeNewsWebsite"
version = "0.1.0"

dependencies = [
    "streamlit>=1.45.0",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "networkx>=3.4.2",
    "matplotlib>=3.10.1",
    "black>=23.0",
]
